sudo: false
language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
- '5'
- '6'
before_script: npm config set coverage true
after_success: npm run-script coveralls
env:
- DEBUG="yeoman:generator"
deploy:
  provider: npm
  email: jan@janraasch.com
  skip_cleanup: true
  api_key:
    secure: YyzwJhcrqhq1sQwuDJGreilRcVED0GnUbmJu766CECknUCDYdJWtJE/M18hiPLTT/T9UQwMdMgd+R4AEJomCGFM1Qx18TKaavsTtrFdvAkC84A3V9LbinMm19nzuSE5G3j6m1bOmyT7JTaBfgWpLGCaWXKNXgzj6yMqoUehECcY=
  on:
    tags: true
    repo: janraasch/generator-gulpplugin-coffee
    node: '4'
    branch: master
